version: '3'
services:
  nginxBABCNfrontend:
    build: ""
    image: nginx-uad-frontend
    container_name: business-assistant-bcn-frontend
    restart: "no"
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: /bin/sh -c "envsubst < ${BASE_PATH}/conf/businessassistantbcn-docker.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
